import {Menu, MenuData} from '@store/global.d'
// import {RouteObject} from 'react-router-dom'
// 在不使用后端接口返回菜单数据的情况下，可以直接在前端配置菜单数据
// ['father/page1/index.tsx', 'father/page2/index.tsx', 'index/index.tsx']
export const menuData: MenuData[] = [
  // ------------------ Home -----------------
  {
    id: 'home',
    name: '首页',
    routePath: 'home',
    link: '/home',
    filePath: 'index/index.tsx',
    // icon: 'Html5Outlined',
    isMenu: true,
    isHeader: true,
    headerHide: true,
  },
  // ----------------- tables -----------------
  {
    id: 'tables',
    name: '表格类型',
    link: '/tables/base',
    icon: 'TableOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: true,
    headerHide: true,
    showKeepAliveTab: true,
  },
  {
    id: 'tables-base',
    parentId: 'tables',
    name: '基础表格',
    routePath: 'tables/base',
    link: '/tables/base',
    filePath: 'tables/base/index.tsx',
    icon: 'TableOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'tables-base-search',
    parentId: 'tables',
    name: '基础搜索',
    routePath: 'tables/base-search',
    link: '/tables/base-search',
    filePath: 'tables/base-search/index.tsx',
    icon: 'SearchOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'tables-system',
    parentId: 'tables',
    name: '系统管理',
    icon: 'SettingOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'tables-system-user-manage',
    parentId: 'tables-system',
    name: '用户管理',
    routePath: 'tables/system/user-manage',
    link: '/tables/system/user-manage',
    filePath: 'tables/user-manage/index.tsx',
    // icon: 'UserOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  // ----------------- forms -----------------
  {
    id: 'forms',
    name: '表单类型',
    link: '/forms/login',
    icon: 'FormOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: true,
    showKeepAliveTab: false,
  },
  {
    id: 'forms-login',
    name: '登录页面',
    parentId: 'forms',
    icon: 'UserOutlined',
    isMenu: true,
  },
  {
    id: 'forms-login-basic',
    name: '基础登录',
    parentId: 'forms-login',
    routePath: 'forms/login',
    link: '/forms/login',
    filePath: 'login/index.tsx',
    isMenu: true,
  },
  // ----------------- layout -----------------
  {
    id: 'layout',
    name: '页面布局',
    link: '/layout/basic',
    icon: 'LayoutOutlined',
    routePath: 'layout/basic',
    filePath: 'index/index.tsx',
    isMenu: true,
    disabeld: false,
    isHeader: true,
    showKeepAliveTab: false,
  },
  // ----------------- charts -----------------
  {
    id: 'charts',
    name: '图表类型',
    link: '/charts/basic',
    filePath: 'index/index.tsx',
    icon: 'BarChartOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: true,
    showKeepAliveTab: false,
  },
  // ----------------- project-demo -----------------
  {
    id: 'project-demo',
    name: '项目演示',
    icon: 'ProjectOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: true,
    showKeepAliveTab: false,
  },
  // ----------------- datalake -----------------
  {
    id: 'datalake',
    parentId: 'project-demo',
    name: '湖仓一体',
    link: '/datalake/nodes',
    icon: 'DatabaseOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: true,
  },
  {
    id: 'datalake-compserver',
    parentId: 'datalake',
    name: '组件管理服务',
    routePath: 'datalake/compserver',
    link: '/datalake/compserver',
    filePath: 'index/index.tsx',
    icon: 'DeploymentUnitOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'datalake-nodes',
    parentId: 'datalake',
    name: '机器节点管理',
    routePath: 'datalake/nodes',
    link: '/datalake/nodes',
    filePath: 'index/index.tsx',
    icon: 'ClusterOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
    headerHide: false,
  },
  {
    id: 'datalake-monitor',
    parentId: 'datalake',
    name: '告警管理服务',
    routePath: 'datalake/monitor',
    link: '/datalake/monitor',
    filePath: 'index/index.tsx',
    icon: 'AlertOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'datalake-data-permission',
    parentId: 'datalake',
    name: '数据权限管理服务',
    routePath: 'datalake/data-permission',
    link: '/datalake/data-permission',
    filePath: 'index/index.tsx',
    icon: 'SafetyOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'datalake-data-manage',
    parentId: 'datalake',
    name: '数据管理服务',
    routePath: 'datalake/data-manage',
    link: '/datalake/data-manage',
    filePath: 'index/index.tsx',
    icon: 'DatabaseOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'datalake-audit',
    parentId: 'datalake',
    name: '审计日志服务',
    routePath: 'datalake/audit',
    link: '/datalake/audit',
    filePath: 'index/index.tsx',
    icon: 'AuditOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'datalake-data-query',
    parentId: 'datalake',
    name: '统一查询服务',
    routePath: 'datalake/data-query',
    link: '/datalake/data-query',
    filePath: 'index/index.tsx',
    icon: 'SearchOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'datalake-mmp',
    parentId: 'datalake',
    name: 'MPP数据库',
    routePath: 'datalake/mmp',
    link: '/datalake/mmp',
    filePath: 'index/index.tsx',
    icon: 'TableOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'datalake-graph',
    parentId: 'datalake',
    name: '图数据库组件',
    routePath: 'datalake/graph',
    link: '/datalake/graph',
    filePath: 'index/index.tsx',
    icon: 'ShareAltOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'datalake-flow-batch',
    parentId: 'datalake',
    name: '流批一体组件',
    routePath: 'datalake/flow-batch',
    link: '/datalake/flow-batch',
    filePath: 'index/index.tsx',
    icon: 'SwapOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'datalake-files',
    parentId: 'datalake',
    name: '分布式文件系统',
    routePath: 'datalake/files',
    link: '/datalake/files',
    filePath: 'index/index.tsx',
    icon: 'FolderOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'datalake-comps',
    parentId: 'datalake',
    name: '湖仓一体组件',
    routePath: 'datalake/comps',
    link: '/datalake/comps',
    filePath: 'index/index.tsx',
    icon: 'AppstoreOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'datalake-archive',
    parentId: 'datalake',
    name: '数据容灾备份管理',
    routePath: 'datalake/archive',
    link: '/datalake/archive',
    filePath: 'index/index.tsx',
    icon: 'CloudSyncOutlined',
    isMenu: true,
    disabeld: false,
  },
  // ----------------- develop -----------------
  {
    id: 'develop',
    parentId: 'project-demo',
    name: '数据中台',
    link: '/develop/datahub',
    icon: 'DatabaseOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: true,
  },
  {
    id: 'develop-datahub',
    parentId: 'develop',
    name: '数据仓库',
    routePath: 'develop/datahub',
    link: '/develop/datahub',
    filePath: 'index/index.tsx',
    icon: 'DatabaseOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-batch',
    parentId: 'develop',
    name: '业务数据标准化',
    routePath: 'develop/batch',
    link: '/develop/batch',
    filePath: 'index/index.tsx',
    icon: 'FileDoneOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-tag',
    parentId: 'develop',
    name: '标签管理',
    routePath: 'develop/tag',
    link: '/develop/tag',
    filePath: 'index/index.tsx',
    icon: 'TagsOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-standard',
    parentId: 'develop',
    name: '数据标准',
    routePath: 'develop/standard',
    link: '/develop/standard',
    filePath: 'index/index.tsx',
    icon: 'FileProtectOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-catalog',
    parentId: 'develop',
    name: '数据资源目录',
    routePath: 'develop/catalog',
    link: '/develop/catalog',
    filePath: 'index/index.tsx',
    icon: 'UnorderedListOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-value',
    parentId: 'develop',
    name: '数据价值管理',
    routePath: 'develop/value',
    link: '/develop/value',
    filePath: 'index/index.tsx',
    icon: 'DollarCircleOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-permission',
    parentId: 'develop',
    name: '权限管理',
    routePath: 'develop/permission',
    link: '/develop/permission',
    filePath: 'index/index.tsx',
    icon: 'SafetyOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-encode',
    parentId: 'develop',
    name: '数据加密',
    routePath: 'develop/encode',
    link: '/develop/encode',
    filePath: 'index/index.tsx',
    icon: 'LockOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-masking',
    parentId: 'develop',
    name: '数据脱敏',
    routePath: 'develop/masking',
    link: '/develop/masking',
    filePath: 'index/index.tsx',
    icon: 'EyeInvisibleOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-operation',
    parentId: 'develop',
    name: '流量管理',
    routePath: 'develop/operation',
    link: '/develop/operation',
    filePath: 'index/index.tsx',
    icon: 'AreaChartOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-server',
    parentId: 'develop',
    name: '数据挂载',
    routePath: 'develop/server',
    link: '/develop/server',
    filePath: 'index/index.tsx',
    icon: 'LinkOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-acl',
    parentId: 'develop',
    name: '访问控制',
    routePath: 'develop/acl',
    link: '/develop/acl',
    filePath: 'index/index.tsx',
    icon: 'SecurityScanOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-share',
    parentId: 'develop',
    name: '数据实体表共享',
    routePath: 'develop/share',
    link: '/develop/share',
    filePath: 'index/index.tsx',
    icon: 'ShareAltOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-role',
    parentId: 'develop',
    name: '角色管理',
    routePath: 'develop/role',
    link: '/develop/role',
    filePath: 'index/index.tsx',
    icon: 'TeamOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-classes',
    parentId: 'develop',
    name: '类别管理',
    routePath: 'develop/classes',
    link: '/develop/classes',
    filePath: 'index/index.tsx',
    icon: 'PartitionOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'develop-model',
    parentId: 'develop',
    name: '数据建模',
    routePath: 'develop/model',
    link: '/develop/model',
    filePath: 'index/index.tsx',
    icon: 'BuildOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  // ----------------- transport -----------------
  {
    id: 'transport',
    parentId: 'project-demo',
    name: '数据采集汇聚',
    link: '/transport/link',
    icon: 'CloudDownloadOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: true,
  },
  {
    id: 'transport-link',
    parentId: 'transport',
    name: '设备连接控制',
    routePath: 'transport/link',
    link: '/transport/link',
    filePath: 'index/index.tsx',
    icon: 'LinkOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'transport-dataSource',
    parentId: 'transport',
    name: '数据源管理',
    routePath: 'transport/dataSource',
    link: '/transport/dataSource',
    filePath: 'index/index.tsx',
    icon: 'DatabaseOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'transport-task',
    parentId: 'transport',
    name: '采集存储任务',
    routePath: 'transport/task',
    link: '/transport/task',
    filePath: 'index/index.tsx',
    icon: 'CloudUploadOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'transport-job',
    parentId: 'transport',
    name: '处理分析任务',
    routePath: 'transport/job',
    link: '/transport/job',
    filePath: 'index/index.tsx',
    icon: 'ConsoleSqlOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'transport-stream',
    parentId: 'transport',
    name: '实时监控',
    routePath: 'transport/stream',
    link: '/transport/stream',
    filePath: 'index/index.tsx',
    icon: 'LineChartOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'transport-debug',
    parentId: 'transport',
    name: '设备控制',
    routePath: 'transport/debug',
    link: '/transport/debug',
    filePath: 'index/index.tsx',
    icon: 'ControlOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'transport-alamConfig',
    parentId: 'transport',
    name: '报警配置',
    routePath: 'transport/alamConfig',
    link: '/transport/alamConfig',
    filePath: 'index/index.tsx',
    icon: 'AlertOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'transport-alamCheck',
    parentId: 'transport',
    name: '报警查询',
    routePath: 'transport/alamCheck',
    link: '/transport/alamCheck',
    filePath: 'index/index.tsx',
    icon: 'SearchOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'transport-monitoring',
    parentId: 'transport',
    name: '设备监控',
    routePath: 'transport/monitoring',
    link: '/transport/monitoring',
    filePath: 'index/index.tsx',
    icon: 'MonitorOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'transport-overview',
    parentId: 'transport',
    name: '任务概览',
    routePath: 'transport/overview',
    link: '/transport/overview',
    filePath: 'index/index.tsx',
    icon: 'FundViewOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  // ----------------- external -----------------
  {
    id: 'external',
    parentId: 'project-demo',
    name: '数据接入',
    link: '/external/origin',
    icon: 'CloudServerOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: true,
  },
  {
    id: 'external-origin',
    parentId: 'external',
    name: '接入来源管理',
    routePath: 'external/origin',
    link: '/external/origin',
    filePath: 'index/index.tsx',
    icon: 'GatewayOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'external-tables',
    parentId: 'external',
    name: '数据模版配置',
    routePath: 'external/tables',
    link: '/external/tables',
    filePath: 'index/index.tsx',
    icon: 'FileTextOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'external-manage',
    parentId: 'external',
    name: '接入数据管理',
    routePath: 'external/manage',
    link: '/external/manage',
    filePath: 'index/index.tsx',
    icon: 'DatabaseOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'external-task',
    parentId: 'external',
    name: '接入任务管理',
    routePath: 'external/task',
    link: '/external/task',
    filePath: 'index/index.tsx',
    icon: 'ScheduleOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'external-schedule',
    parentId: 'external',
    name: '接入调度管理',
    routePath: 'external/schedule',
    link: '/external/schedule',
    filePath: 'index/index.tsx',
    icon: 'SyncOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'external-share',
    parentId: 'external',
    name: '数据共享管理',
    routePath: 'external/share',
    link: '/external/share',
    filePath: 'index/index.tsx',
    icon: 'ShareAltOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  // ----------------- asset-tools -----------------
  {
    id: 'asset-tools',
    parentId: 'project-demo',
    name: '支撑工具',
    link: '/asset-tools/model-manage',
    icon: 'ToolOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: true,
  },
  {
    id: 'asset-tools-model-manage',
    parentId: 'asset-tools',
    name: '资源模型管理',
    routePath: 'asset-tools/model-manage',
    link: '/asset-tools/model-manage',
    filePath: 'index/index.tsx',
    icon: 'BuildOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'asset-tools-model-rules-verify',
    parentId: 'asset-tools',
    name: '模型校验',
    routePath: 'asset-tools/model-rules-verify',
    link: '/asset-tools/model-rules-verify',
    filePath: 'index/index.tsx',
    icon: 'CheckCircleOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'asset-tools-meta-model',
    parentId: 'asset-tools',
    name: '采集适配器管理',
    routePath: 'asset-tools/meta-model',
    link: '/asset-tools/meta-model',
    filePath: 'index/index.tsx',
    icon: 'ApiOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'asset-tools-meta-query',
    parentId: 'asset-tools',
    name: '技术元数据',
    routePath: 'asset-tools/meta-query',
    link: '/asset-tools/meta-query',
    filePath: 'index/index.tsx',
    icon: 'CodeOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'asset-tools-meta-monitor',
    parentId: 'asset-tools',
    name: '元数据监控',
    routePath: 'asset-tools/meta-monitor',
    link: '/asset-tools/meta-monitor',
    filePath: 'index/index.tsx',
    icon: 'MonitorOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'asset-tools-lineage',
    parentId: 'asset-tools',
    name: '血缘分析',
    routePath: 'asset-tools/lineage',
    link: '/asset-tools/lineage',
    filePath: 'index/index.tsx',
    icon: 'ClusterOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'asset-tools-report',
    parentId: 'asset-tools',
    name: '报告查询与下载',
    routePath: 'asset-tools/report',
    link: '/asset-tools/report',
    filePath: 'index/index.tsx',
    icon: 'FilePdfOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  // ----------------- resource -----------------
  {
    id: 'resource',
    parentId: 'project-demo',
    name: '服务支撑',
    link: '/resource/deploy',
    icon: 'CloudServerOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: true,
  },
  {
    id: 'resource-deploy',
    parentId: 'resource',
    name: '平台运维管理',
    routePath: 'resource/deploy',
    link: '/resource/deploy',
    filePath: 'index/index.tsx',
    icon: 'SettingOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'resource-storage',
    parentId: 'resource',
    name: '存储服务',
    routePath: 'resource/storage',
    link: '/resource/storage',
    filePath: 'index/index.tsx',
    icon: 'DatabaseOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'resource-batch',
    parentId: 'resource',
    name: '离线计算服务',
    routePath: 'resource/batch',
    link: '/resource/batch',
    filePath: 'index/index.tsx',
    icon: 'ConsoleSqlOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'resource-stream',
    parentId: 'resource',
    name: '实时计算服务',
    routePath: 'resource/stream',
    link: '/resource/stream',
    filePath: 'index/index.tsx',
    icon: 'RocketOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  // ----------------- exchange -----------------
  {
    id: 'exchange',
    parentId: 'project-demo',
    name: '数据交换',
    link: '/exchange/schedule',
    icon: 'SwapOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: true,
  },

  {
    id: 'exchange-schedule',
    parentId: 'exchange',
    name: '调度引擎',
    routePath: 'exchange/schedule',
    link: '/exchange/schedule',
    filePath: 'index/index.tsx',
    icon: 'ScheduleOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'exchange-exchange',
    parentId: 'exchange',
    name: '交换引擎',
    routePath: 'exchange/exchange',
    link: '/exchange/exchange',
    filePath: 'index/index.tsx',
    icon: 'SwapOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'exchange-proxy',
    name: '管理代理',
    parentId: 'exchange',
    routePath: 'exchange/proxy',
    link: '/exchange/proxy',
    filePath: 'index/index.tsx',
    icon: 'GatewayOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'exchange-gatewayConfiguration',
    parentId: 'exchange',
    name: '交换配置',
    routePath: 'exchange/gatewayConfiguration',
    link: '/exchange/gatewayConfiguration',
    filePath: 'index/index.tsx',
    icon: 'SettingOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'exchange-centerWatch',
    parentId: 'exchange',
    name: '运行监控',
    routePath: 'exchange/centerWatch',
    link: '/exchange/centerWatch',
    filePath: 'index/index.tsx',
    icon: 'MonitorOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
  {
    id: 'exchange-dataMenu',
    parentId: 'exchange',
    name: '交换目录',
    routePath: 'exchange/dataMenu',
    link: '/exchange/dataMenu',
    filePath: 'index/index.tsx',
    icon: 'UnorderedListOutlined',
    isMenu: true,
    disabeld: false,
    isHeader: false,
  },
]
